### ISSUE TITLE
Implement missing methods in AerospikeClient

### ISSUE THREAD

**Issue by srini156** [srini156/mock-aerospike#4]
Implement the following
- touch
- prepend
- append
- add

**Comment by vVv-AA** [comment]
I'd like to do this if its not an issue. Also, can you give the exception message for touch function?

**Comment by srini156** [comment]
@vVv-AA - please proceed with implementation and raise a PR. Not entirely aware of the context of the exception message, but I will check and add that to PR.

**Comment by vVv-AA** [comment]
Have written the code, waiting for 1st Oct. Will send PR for review tomorrow.

**Comment by srini156** [comment]
PR - #15
